// <auto-generated />
using System;
using Escola.Infra.EF;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Escolas.Infra.EF.Migrations
{
    [DbContext(typeof(EscolaContextoEF))]
    partial class EscolaContextoEFModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:matriculas.pessoaseq", "'pessoaseq', 'matriculas', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Escola.Dominio.Alunos.Aluno", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:HiLoSequenceName", "pessoaseq")
                        .HasAnnotation("SqlServer:HiLoSequenceSchema", "matriculas")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.SequenceHiLo);

                    b.Property<DateTime>("DataNascimento")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Sexo")
                        .IsRequired()
                        .HasColumnType("varchar(15)");

                    b.HasKey("Id");

                    b.ToTable("Alunos","matriculas");
                });

            modelBuilder.Entity("Escola.Dominio.Alunos.Aluno", b =>
                {
                    b.OwnsOne("Escola.Dominio.Shared.NomeAluno", "Nome", b1 =>
                        {
                            b1.Property<long>("AlunoId")
                                .HasColumnType("bigint");

                            b1.Property<string>("Primeiro")
                                .HasColumnName("PrimeiroNome")
                                .HasColumnType("varchar(20)");

                            b1.Property<string>("Sobrenome")
                                .HasColumnName("Sobrenome")
                                .HasColumnType("varchar(40)");

                            b1.HasKey("AlunoId");

                            b1.ToTable("Alunos");

                            b1.WithOwner()
                                .HasForeignKey("AlunoId");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
